# for test
version: '3.3'

services:
  couchdb:
    image: apache/couchdb
    volumes:
      - ./tmp/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: test
      COUCHDB_PASSWORD: verystrongpassword
    ports:
      - 15984:5984

  server:
    image: hanpama/sewoon-on-the-web-server
    build: .