version: '3'
services:

  # postgres:
  #   image: "postgres:9.6.1"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: "test"
  #     POSTGRES_PASSWORD: "test"
  #     POSTGRES_DB: "test"

  sow_server:
    image: hanpama/c2g
    volumes:
    - ./test:/var/app/test
    - ./src:/var/app/src
    command: npm run test
